export const ROUTES_OWNER = {
  BASE: "/",
  LOGIN: "/auth/login",

  MAIN_DASHBOARD: "/owner",
  PHARMACIES: "/owner/pharmacies",
  COMPANIES: "/owner/companies",
  PRODUCTS: "/owner/products",
  CATEGORIES: "/owner/categories",
  BRANDS: "/owner/brands",
  LOCATIONS: "/owner/locations",
  BRANCHES: "/owner/branches",
  PHARMACISTS: "/owner/pharmacists",
  ADMINS: "/owner/admins",
  SLIDERS: "/owner/slider",
  ROLES: "/owner/roles",
  PRODUCT_REQUESTS: "/owner/product-requests"
};

export const ROUTES_PHARMA = {
  DASHBOARD: "/pharma",
  STAGNANT_GOODS: "/pharma/stagnant-goods",
  DAY_ORDERS: "/pharma/today",
  SENT_ORDERS: "/pharma/sentorder",
  MY_ORDERS: "/pharma/massgeorder",
  INVOICE: "/pharma/invoice",
  ATTRIBUTES: "/pharma/attributes",
  PRODUCTS: "/pharma/products",
  PROFILE: "/pharma/profile",
  SETTINGS: "/pharma/settings",
  TRASH: "/pharma/trash",
  OFFERS: "/pharma/offers",
  COUPONS: "/pharma/coupons",
  DISCOUNT: "/pharma/discount",
  CART: "/pharma/cart",
  COMPANIESPRODUCTS: "/pharma/companies-products",
  COMPANIES: "/pharma/warehouse",
  BRANCHES: "/pharma/branches",
  ADD_EMPLOYEE: "/pharma/add-employee",
  SYSTEM: "/pharma/system",
  BRANCH: (id: number) => `/pharma/branches/${id}`,
  BUY_INVOICES:"/pharma/offline_invoices/buy",
  SELL_INVOICES:"/pharma/offline_invoices/sell",
};

export const ROUTES_COMPANY = {
  DASHBOARD: "/company",
  DAY_ORDERS: "/company/today",
  SENT_ORDERS: "/company/sentorder",
  MY_ORDERS: "/company/massgeorder",
  INVOICE: "/company/invoice",
  ATTRIBUTES: "/company/attributes",
  PRODUCTS: "/company/products",
  TRASH: "/company/trash",
  PROFILE: "/company/profile",
  SETTINGS: "/company/settings",
  ROLES: "/company/settings/roles",
  LOCATIONS: "/company/settings/locations",
  ADD_EMPLOYEE: "/company/add-employee",
  ADD_PHARMACY: "/company/add-pharmacy",
  SYSTEM: "/company/system",
  WAREHOUSES: "/company/warehouse",
  ADMINISTRATION: "/company/administration",
  OFFERS: "/company/offers",
  PHARMACIES_ORDERS: "/company/pharmacies-orders",
  REQUESTS_PRODUCTS:'/company/products/request',
  NEW_PRODUCT_REQ: '/company/products/request/new',
  BUY_INVOICES:"/company/offline_invoices/buy",
  SELL_INVOICES:"/company/offline_invoices/sell"

};
